/** Generated by TAP **/
KISSY.config({
    "modules": {
        "vr/cube": {
            "requires": [
                "dom",
                "event",
                "vr/touch",
                "vr/orientation"
            ]
        }
    },
    "packages": {
        "dragon-tv": {
            "debug": true,
            "ignorePackageNameInUri": true,
            "path": "http://g.assets.daily.taobao.net/tmapp/dragon-tv/1.0.7/js/",
            "version": "1.0.7"
        }
    }
});